### ISSUE TITLE
Not working after logout.

### ISSUE THREAD

**Issue by sagliksever** [tlovett1/simple-cache#1]
my website [Sağlık](http://www.sagliksever.com) i install simple cache plugin but after logout in admin panel not working for me simple cache. How to fix this?

**Comment by tlovett1** [comment]
Can you provide more details please?

**Comment by sagliksever** [comment]
Thank you new update work. but now 1 more problem bbpress i open new post get HTTP ERROR 500 with simple cache

**Comment by sagliksever** [comment]
And 1 more ![sagliksever](https://cloud.githubusercontent.com/assets/18511203/15089759/fe8d1e50-1413-11e6-8429-6320fd64e449.png)

Every purge cache or start stop cache wp-config.php space

**Comment by tlovett1** [comment]
Included in 1.4.1. Thanks!
