### ISSUE TITLE
Mass comment deletion doesn't work

### ISSUE THREAD

**Issue by ding0z** [tlovett1/simple-cache#105]
When pressed "empty the bin" of the comments the site returns an error.

`Error Details
====================
An error of E_ERROR is caused in the line 59 of the file /public_html/site/wp-content/plugins/simple-cache/inc/class-sc-advanced-cache.php. 
Error Message: Uncaught Error: Call to undefined function sc_get_cache_path() in /public_html/site/wp-content/plugins/simple-cache/inc/class-sc-advanced-cache.php:59
Stack trace:
#0 /public_html/site/wp-includes/class-wp-hook.php(290): SC_Advanced_Cache->purge_post_on_comment_status_change('2809')
#1 /public_html/site/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#2 /public_html/site/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /public_html/site/wp-includes/comment.php(1439): do_action('wp_set_comment_...', '2809', 'delete')
#4 /public_html/site/wp-admin/edit-comments.php(86): wp_delete_comment('2809')
#5 {main}
  thrown`

**Comment by tlovett1** [comment]
Should be fixed in 1.7.2
