### ISSUE TITLE
Ability to preload cache

### ISSUE THREAD

**Issue by denizdogan** [tlovett1/simple-cache#12]
Thanks for this plugin, I'm really loving the simplicity of it. Would it be possible to add something simple which preloads non-cached or expired pages?

**Comment by tlovett1** [comment]
Possibly in the future.

**Comment by LogoLogics2** [comment]
That would be great!

**Comment by chuckreynolds** [comment]
#27 official

**Comment by denizdogan** [comment]
Fair enough, go with #27, closing
