### ISSUE TITLE
HTML labels not working on the settings page

### ISSUE THREAD

**Issue by swissspidy** [tlovett1/simple-cache#13]
The following `<label>` tags aren't working on the settings page:

* Enable Page Caching
* Expire page cache after
* Enable gzip Compression

For example, the `for` attribute for the 'Enable gzip Compression' label is `sc_enable_gzip_compression`, but the `id` attribute of the `<input>` element is `sc_enable_gzip_compression_advanced`.

That's why nothing happens when clicking on the label.

**Comment by tlovett1** [comment]
Would love a PR :)
