### ISSUE TITLE
No caching HTTP headers for cached pages 

### ISSUE THREAD

**Issue by spotman** [tlovett1/simple-cache#2]
Hi, Taylor!

Thanks for this amazing plugin, it's really simple and useful! But it seems that cached pages have no `Last-Modified`, `Expires` and other HTTP caching headers (but they exists for non-cached versions, I think WP is generating them by default). The caching is enabled in admin page (the first option is "Yes", all other options are in their default states).

Is this a bug? Or am I missing something in config?

**Comment by tlovett1** [comment]
This is a bug (I think). I'm thinking about how to address. We can set HTTP headers but then early cache invalidation will not work.

**Comment by tlovett1** [comment]
Check out that commit and tell me what you think.

**Comment by spotman** [comment]
Hi, Taylor!

Thanks for response. I've commented your commit.
