### ISSUE TITLE
Batcache

### ISSUE THREAD

**Issue by wrrr** [tlovett1/simple-cache#21]
I put the dropin batcache.php in /wp-content

I see it exists in your /inc/dropins as well. Pardon my ignorance but which one controls the batcache if you want to change for instance - var $max_age = 3600; ?

Awesome performing plugin. 
Thanks
stu

**Comment by tlovett1** [comment]
You can't use a custom batcache.php file with Simple Cache. If you want to change max age, you'll probably need to write a PR to make it a configurable option.
