### ISSUE TITLE
.Woff and svg caching

### ISSUE THREAD

**Issue by tatof** [tlovett1/simple-cache#31]
Hello,

Great plugin, but what does it cache?
When I look in google pagespeed insight I'm missing the .woff, .svg and some .png in my cache.

How can I fix this?
I've added this to the .htaccess, but it feels a bit double:

Header unset Pragma
FileETag None
Header unset ETag

---- IfModule mod_expires.c

AddType application/vnd.ms-fontobject .eot 
AddType application/x-font-ttf .ttf
AddType application/x-font-opentype .otf
AddType application/x-font-woff .woff
AddType image/svg+xml .svg

ExpiresActive On
ExpiresByType image/jpg "access 1 year"
ExpiresByType image/jpeg "access 1 year"
ExpiresByType image/gif "access 1 year"
ExpiresByType image/png "access 1 year"
ExpiresByType text/css "access 1 month"
ExpiresByType text/html "access 1 month"
ExpiresByType application/pdf "access 1 month"
ExpiresByType text/x-javascript "access 1 month"
ExpiresByType application/x-shockwave-flash "access 1 month"
ExpiresByType image/x-icon "access 1 year"
ExpiresDefault "access 1 month"
ExpiresByType application/vnd.ms-fontobject "access plus 1 year"
ExpiresByType application/x-font-ttf "access plus 1 year"
ExpiresByType application/x-font-opentype "access plus 1 year"
ExpiresByType application/x-font-woff "access plus 1 year"
ExpiresByType image/svg+xml "access plus 1 year"

----- IfModule

**Comment by tlovett1** [comment]
The plugin doesn't cache static files like images. You should handle that at the server level. It can handle object caching and page caching.
