### ISSUE TITLE
Wrong admin notice

### ISSUE THREAD

**Issue by mustafauysal** [tlovett1/simple-cache#5]
Somehow I'm getting 
<img width="1098" alt="screen shot 2016-05-18 at 09 41 08" src="https://cloud.githubusercontent.com/assets/1421387/15349617/b9521396-1cdc-11e6-8a1b-a71d0b7695c2.png">

Meanwhile I'm seeing
`define( 'WP_CACHE', true ); // Simple Cache`

in wp-config file.

**Comment by tlovett1** [comment]
Was advanced-cache.php edited?

**Comment by mustafauysal** [comment]
No, I didn't edit and can't repeat this issue.

Please ignore this issue and mark as invalid. I'll re-open if needed.
