### ISSUE TITLE
"Uglified" wp-config.php when on/off the cache

### ISSUE THREAD

**Issue by alx359** [tlovett1/simple-cache#89]
Enabling/disabling the cache adds `define( 'WP_CACHE', true|false );` directive on top of `wp-config.php`, but also adds an extra new line to each other line in the file which "uglifies" the code layout. (Tested on WAMP, but Notepad++ shows the file as being `Unix (LF)`.) 

In `\simple-cache\inc\class-sc-advanced-cache.php line 320`
changing this:
`if ( ! $wp_filesystem->put_contents( $config_path, implode( "\n\r", $config_file ), FS_CHMOD_FILE ) ) {`
to this:
`if ( ! $wp_filesystem->put_contents( $config_path, implode( PHP_EOL, $config_file ), FS_CHMOD_FILE ) ) {`
fixes that issue for me (but also takes some other extra lines away); at least it should be more consistent by being platform agnostic. 

Other way would be to show a button-notice and let the admin the choice to fix it manually first.

Thanks.

**Comment by stefanos82** [comment]
@alx359 in my case another thing is happening. When I first installed it, it added `^M` and remove the newline at the very end of `wp-config.php`.

Also, it complained that it did not find the `WP_CACHE` inside the file, even though it was added at the very top of the file, right beneath the opening PHP tag and asked me to fix it by pressing a button.

Is this behavior normal @tlovett1 ? Please advice.

**Comment by chuckreynolds** [comment]
ditto ^^

**Comment by tlovett1** [comment]
This should be fixed now.
