### ISSUE TITLE
not recognizing memcached on php 7? 

### ISSUE THREAD

**Issue by chuckreynolds** [tlovett1/simple-cache#9]
In plugin settings I get this: 

> Neither Memcache or Redis PHP extensions are set up on your server.

Setup (used laravel forge):
* Memcached Version 3.0.0b1
* PHP Version 7.0.4-1+deb.sury.org~trusty+1

Thoughts?

**Comment by tlovett1** [comment]
You need the "Memcache" PHP extension not Memcached. This message will be made more clear in the next version.

**Comment by chuckreynolds** [comment]
Ah. i c.
